### ISSUE TITLE
Stressnet nodes banning each other

### ISSUE THREAD

**Issue by nahuhh** [seraphis-migration/monero#180]
Nodes on stressnet seem to be banning each other. Below are logs from 2 nodes, one banning and one banned. Bans have been reported by probably 4 or 5 people.

<details>
<summary>logs from banning node</summary>

```
2025-10-14 19:39:20.180 [RPC0]  INFO    perf.blockchain src/common/perf_timer.cpp:156   PERF        3          expand_transaction_2
2025-10-14 19:39:20.221 [P2P1]  DEBUG   net.cn  src/cryptonote_protocol/cryptonote_protocol_handler.inl:1716    [172.103.161.225:28080 OUT] requesting callback
2025-10-14 19:39:20.221 [P2P1]  INFO    net.cn  src/cryptonote_protocol/cryptonote_protocol_handler.inl:1719    [172.103.161.225:28080 OUT] [0] state: requesting callback in state synchronizing
2025-10-14 19:39:20.221 [P2P3]  DEBUG   net.cn  src/cryptonote_protocol/cryptonote_protocol_handler.inl:234     [172.103.161.225:28080 OUT] callback fired
2025-10-14 19:39:20.221 [P2P3]  INFO    net.cn  src/cryptonote_protocol/cryptonote_protocol_handler.inl:259     [172.103.161.225:28080 OUT] dropping idle peer with negative score
2025-10-14 19:39:20.221 [P2P3]  DEBUG   net.cn  src/cryptonote_protocol/cryptonote_protocol_handler.inl:2812    [172.103.161.225:28080 OUT] dropping connection id 4d0d16e3-1ff1-40a3-a6a7-af0d8a92336c (pruning seed 0), score 5, flush_all_spans 0
2025-10-14 19:39:20.221 [P2P3]  DEBUG   net.p2p src/p2p/net_node.inl:413        Host 172.103.161.225 fail score=15
2025-10-14 19:39:20.222 [P2P3]  INFO    net     contrib/epee/include/storages/levin_abstract_invoke2.h:74       Failed to invoke command 1002 return code -3
2025-10-14 19:39:20.222 [P2P3]  WARNING net.p2p src/p2p/net_node.inl:1281       [172.103.161.225:28080 OUT] COMMAND_TIMED_SYNC invoke failed. (-3, LEVIN_ERROR_CONNECTION_DESTROYED)
2025-10-14 19:39:20.222 [P2P3]  INFO    global  src/p2p/net_node.inl:324        Host 172.103.161.225 blocked.
2025-10-14 19:39:20.222 [P2P3]  INFO    net.cn  src/cryptonote_protocol/cryptonote_protocol_handler.inl:2886    [172.103.161.225:28080 OUT] [0] state: closed in state synchronizing
2025-10-14 19:39:20.222 [P2P3]  INFO    net.p2p src/p2p/net_node.inl:2717       [172.103.161.225:28080 4d0d16e3-1ff1-40a3-a6a7-af0d8a92336c OUT] CLOSE CONNECTION
```
</details>

<details>
<summary>logs from banned node</summary>

```
2025-10-14 19:38:26.985	[P2P8]	WARNING	net.p2p	src/p2p/net_node.inl:1301	[185.141.216.177:28180 OUT] COMMAND_TIMED_SYNC Failed
2025-10-14 19:38:26.986	[P2P8]	INFO	net.p2p.traffic	contrib/epee/include/net/levin_protocol_handler_async.h:56	[185.141.216.177:58594 INC] 172 bytes sent for category command-1002 initiated by us
2025-10-14 19:38:26.987	[P2P8]	DEBUG	net	contrib/epee/include/net/levin_protocol_handler_async.h:148	[185.141.216.177:58594 INC] LEVIN_PACKET_SENT. [len=172, flags1, r?=, cmd = 1002, ver=1
2025-10-14 19:38:26.987	[P2P8]	DEBUG	net	contrib/epee/include/net/levin_protocol_handler_async.h:199	[185.141.216.177:58594 INC] anvoke_handler, timeout: 120000
2025-10-14 19:38:26.988	[P2P8]	ERROR	net	contrib/epee/include/net/levin_protocol_handler_async.h:625	[185.141.216.177:51452 INC] Failed to do_send
2025-10-14 19:38:26.989	[P2P8]	WARNING	net.p2p	src/p2p/net_node.inl:1281	[185.141.216.177:51452 INC] COMMAND_TIMED_SYNC invoke failed. (-1, LEVIN_ERROR_CONNECTION)
2025-10-14 19:38:26.990	[P2P8]	WARNING	net.p2p	src/p2p/net_node.inl:1301	[185.141.216.177:51452 INC] COMMAND_TIMED_SYNC Failed
2025-10-14 19:39:21.526	[P2P8]	DEBUG	net	contrib/epee/include/net/levin_protocol_handler_async.h:489	[185.141.216.177:58594 INC] LEVIN_PACKET_RECEIVED. [len=7657, flags1, r?=, cmd = 2002, v=1
2025-10-14 19:39:21.527	[P2P8]	INFO	net.p2p.traffic	contrib/epee/include/net/levin_protocol_handler_async.h:56	[185.141.216.177:58594 INC] 7657 bytes received for category command-2002 initiated by peer
2025-10-14 19:39:21.527	[P2P8]	INFO	net.p2p.msg	src/cryptonote_protocol/cryptonote_protocol_handler.inl:901	[185.141.216.177:58594 INC] Received NOTIFY_NEW_TRANSACTIONS (1 txes)
2025-10-14 19:39:22.773	[P2P3]	DEBUG	net.cn	src/cryptonote_protocol/cryptonote_protocol_handler.inl:1588	[185.141.216.177:28180 OUT] Block process time (1 blocks, 800 txs): 1220 (153/1067) ms
2025-10-14 19:39:22.960	[P2P3]	DEBUG	net.cn	src/cryptonote_protocol/cryptonote_protocol_handler.inl:1389	[185.141.216.177:28180 OUT]  next span in the queue has blocks 2854509-2854509, we need 2854510
2025-10-14 19:39:29.481	[P2P1]	ERROR	net	contrib/epee/include/net/levin_protocol_handler_async.h:625	[185.141.216.177:28180 OUT] Failed to do_send
2025-10-14 19:39:29.482	[P2P1]	WARNING	net.p2p	src/p2p/net_node.inl:1281	[185.141.216.177:28180 OUT] COMMAND_TIMED_SYNC invoke failed. (-1, LEVIN_ERROR_CONNECTION)
2025-10-14 19:39:29.483	[P2P1]	WARNING	net.p2p	src/p2p/net_node.inl:1301	[185.141.216.177:28180 OUT] COMMAND_TIMED_SYNC Failed
2025-10-14 19:39:29.486	[P2P1]	ERROR	net	contrib/epee/include/net/levin_protocol_handler_async.h:625	[185.141.216.177:51452 INC] Failed to do_send
2025-10-14 19:39:29.487	[P2P1]	WARNING	net.p2p	src/p2p/net_node.inl:1281	[185.141.216.177:51452 INC] COMMAND_TIMED_SYNC invoke failed. (-1, LEVIN_ERROR_CONNECTION)
2025-10-14 19:39:29.488	[P2P1]	WARNING	net.p2p	src/p2p/net_node.inl:1301	[185.141.216.177:51452 INC] COMMAND_TIMED_SYNC Failed
2025-10-14 19:39:29.535	[P2P5]	INFO	net.p2p	src/p2p/net_node.inl:2698	[185.141.216.177:43102 82477ab6-fb8b-4fec-8124-b0be8a137744 INC] NEW CONNECTION
2025-10-14 19:39:29.535	[P2P5]	DEBUG	net	contrib/epee/include/net/abstract_tcp_server2.inl:1059	 connection type 2 192.168.1.229:28080 <--> 185.141.216.177:43102 (via 185.141.216.177:43102)
2025-10-14 19:39:29.535	[P2P7]	INFO	net.cn	src/cryptonote_protocol/cryptonote_protocol_handler.inl:2882	[185.141.216.177:43102 INC] [0] state: closed in state before_handshake
2025-10-14 19:39:29.536	[P2P7]	INFO	net.p2p	src/p2p/net_node.inl:2717	[185.141.216.177:43102 82477ab6-fb8b-4fec-8124-b0be8a137744 INC] CLOSE CONNECTION
2025-10-14 19:39:32.272	[P2P1]	INFO	net.p2p	src/p2p/net_node.inl:2698	[185.141.216.177:46730 37b3489c-36e1-43b9-8e03-13e9a57012a3 INC] NEW CONNECTION
2025-10-14 19:39:32.272	[P2P1]	DEBUG	net	contrib/epee/include/net/abstract_tcp_server2.inl:1059	 connection type 2 192.168.1.229:28080 <--> 185.141.216.177:46730 (via 185.141.216.177:46730)
2025-10-14 19:39:32.273	[P2P7]	INFO	net.cn	src/cryptonote_protocol/cryptonote_protocol_handler.inl:2882	[185.141.216.177:46730 INC] [0] state: closed in state before_handshake
2025-10-14 19:39:32.273	[P2P7]	INFO	net.p2p	src/p2p/net_node.inl:2717	[185.141.216.177:46730 37b3489c-36e1-43b9-8e03-13e9a57012a3 INC] CLOSE CONNECTION
```
</details>

**Comment by j-berman** [comment]
My initial hunch from the logs is that the banned node's connection is getting overloaded with writes [here](https://github.com/monero-project/monero/blob/d32b5bfe18e2f5b979fa8dc3a8966c76159ca722/contrib/epee/include/net/abstract_tcp_server2.inl#L768-L868), and isn't able to handle it.

I would like to see if nodes running #177, #156, and #169 still experience this issue. I'm about to post a release that includes #156 and #169. While PR #177 is still in review.

**Comment by coffnix** [comment]
I wrote a small shell script unban-testnet-monero.sh that polls your local monerod JSON-RPC for currently banned IPs, and automatically removes each ban via set_bans (ban:false). The script is silent by default, it only appends to the logfile when there is at least one IP to unban, so it’s safe to run frequently from cron without polluting logs.

What it does
	•	Calls get_bans on your local monerod RPC.
	•	Extracts the list of host entries.
	•	For each host found, issues a set_bans request with ban:false.
	•	Logs start/finish and each unban only when there were bans to remove.

Dependencies
	•	curl
	•	jq (for JSON parsing)
	•	monerod reachable at the RPC URL you configure, and the user running the script must be allowed to access that RPC (adjust auth if required).

Quick install
	1.	Put the script at e.g. ~/unban-testnet-monero.sh (or another path).
	2.	Make it executable:

```
#!/bin/bash
# Script: unban-testnet-monero.sh
# Author: coffnix
# Purpose: Automatically unban all banned IPs from monerod testnet using JSON-RPC
# Behavior: Runs silently unless one or more IPs are unbanned

RPC_URL="http://127.0.0.1:28081/json_rpc"
LOGFILE="$HOME/unban-testnet-monero.log"

# Fetch banned IPs safely (handles null -> empty list)
IPS=$(curl -s "$RPC_URL" \
  -H 'Content-Type: application/json' \
  -d '{"jsonrpc":"2.0","id":"0","method":"get_bans"}' \
  | jq -r '.result.bans // [] | .[].host')

# Exit silently if there are no bans
if [ -z "$IPS" ]; then
  exit 0
fi

# Log only if there are bans
{
  echo "===== $(date '+%Y-%m-%d %H:%M:%S') Unbanning process started ====="

  for IP in $IPS; do
    echo "$(date '+%H:%M:%S') Unbanning $IP..."
    curl -s "$RPC_URL" \
      -H 'Content-Type: application/json' \
      -d "{\"jsonrpc\":\"2.0\",\"id\":\"0\",\"method\":\"set_bans\",\"params\":{\"bans\":[{\"host\":\"$IP\",\"ban\":false}]}}"
    echo ""
  done

  echo "===== $(date '+%Y-%m-%d %H:%M:%S') Process finished ====="
  echo ""

} >> "$LOGFILE" 2>&1
```

`chmod +x ~/unban-testnet-monero.sh`

Cron recommendation
If you want the script to keep your testnet node clean automatically, add this cron entry to the user that runs monerod:

Open the crontab:
`crontab -e`

Add this line to run every minute:
`* * * * * ~/unban-testnet-monero.sh`

**Comment by nahuhh** [comment]
Some people have reported bans during IBD on the latest 1.4 release


```
2025-11-08 00:55:10.424 [P2P8]  INFO    net.p2p.traffic contrib/epee/include/net/levin_protocol_handler_async.h:56      [202.169.99.195:28080 OUT] 410440 bytes received for category command-2007 initiated by peer                   
2025-11-08 00:55:10.424 [P2P8]  INFO    net.p2p.msg     src/cryptonote_protocol/cryptonote_protocol_handler.inl:2515    [202.169.99.195:28080 OUT] Received NOTIFY_RESPONSE_CHAIN_ENTRY: m_block_ids.size()=10000, m_start_height=2852821, m_total_height=2871522
2025-11-08 00:55:10.424 [P2P8]  INFO    net.cn  src/cryptonote_protocol/cryptonote_protocol_handler.inl:2517    [202.169.99.195:28080 OUT] [0] state: received chain in state synchronizing                                                                            
2025-11-08 00:55:10.424 [P2P8]  ERROR   net.cn  src/cryptonote_protocol/cryptonote_protocol_handler.inl:2528    [202.169.99.195:28080 OUT] Got NOTIFY_RESPONSE_CHAIN_ENTRY past expected height, dropping connection                   
2025-11-08 00:55:10.424 [P2P8]  DEBUG   net.cn  src/cryptonote_protocol/cryptonote_protocol_handler.inl:2858    [202.169.99.195:28080 OUT] dropping connection id 6bcc717a-e826-43cf-97a7-4fa1b4e20e59 (pruning seed 0), score 1, flush_all_spans 0
2025-11-08 00:55:10.424 [P2P8]  DEBUG   net.p2p src/p2p/net_node.inl:413        Host 202.169.99.195 fail score=11                                                                                                                     
2025-11-08 00:55:10.425 [P2P8]  INFO    global  src/p2p/net_node.inl:324        Host 202.169.99.195 blocked.                                                                                                                          
2025-11-08 00:55:10.425 [P2P8]  INFO    net.cn  src/cryptonote_protocol/cryptonote_protocol_handler.inl:2932    [202.169.99.195:28080 OUT] [0] state: closed in state synchronizing     
2025-11-08 00:55:10.425 [P2P8]  INFO    net.p2p src/p2p/net_node.inl:2798       [202.169.99.195:28080 6bcc717a-e826-43cf-97a7-4fa1b4e20e59 OUT] CLOSE CONNECTION                                                                      
2025-11-08 00:55:10.426 [P2P8]  DEBUG   net.conn        contrib/epee/src/connection_basic.cpp:177       Destructing connection #1295 to 0.0.0.0   
```

**Comment by coffnix** [comment]
> Some people have reported bans during IBD on the latest 1.4 release
> 
> ```
> 2025-11-08 00:55:10.424 [P2P8]  INFO    net.p2p.traffic contrib/epee/include/net/levin_protocol_handler_async.h:56      [202.169.99.195:28080 OUT] 410440 bytes received for category command-2007 initiated by peer                   
> 2025-11-08 00:55:10.424 [P2P8]  INFO    net.p2p.msg     src/cryptonote_protocol/cryptonote_protocol_handler.inl:2515    [202.169.99.195:28080 OUT] Received NOTIFY_RESPONSE_CHAIN_ENTRY: m_block_ids.size()=10000, m_start_height=2852821, m_total_height=2871522
> 2025-11-08 00:55:10.424 [P2P8]  INFO    net.cn  src/cryptonote_protocol/cryptonote_protocol_handler.inl:2517    [202.169.99.195:28080 OUT] [0] state: received chain in state synchronizing                                                                            
> 2025-11-08 00:55:10.424 [P2P8]  ERROR   net.cn  src/cryptonote_protocol/cryptonote_protocol_handler.inl:2528    [202.169.99.195:28080 OUT] Got NOTIFY_RESPONSE_CHAIN_ENTRY past expected height, dropping connection                   
> 2025-11-08 00:55:10.424 [P2P8]  DEBUG   net.cn  src/cryptonote_protocol/cryptonote_protocol_handler.inl:2858    [202.169.99.195:28080 OUT] dropping connection id 6bcc717a-e826-43cf-97a7-4fa1b4e20e59 (pruning seed 0), score 1, flush_all_spans 0
> 2025-11-08 00:55:10.424 [P2P8]  DEBUG   net.p2p src/p2p/net_node.inl:413        Host 202.169.99.195 fail score=11                                                                                                                     
> 2025-11-08 00:55:10.425 [P2P8]  INFO    global  src/p2p/net_node.inl:324        Host 202.169.99.195 blocked.                                                                                                                          
> 2025-11-08 00:55:10.425 [P2P8]  INFO    net.cn  src/cryptonote_protocol/cryptonote_protocol_handler.inl:2932    [202.169.99.195:28080 OUT] [0] state: closed in state synchronizing     
> 2025-11-08 00:55:10.425 [P2P8]  INFO    net.p2p src/p2p/net_node.inl:2798       [202.169.99.195:28080 6bcc717a-e826-43cf-97a7-4fa1b4e20e59 OUT] CLOSE CONNECTION                                                                      
> 2025-11-08 00:55:10.426 [P2P8]  DEBUG   net.conn        contrib/epee/src/connection_basic.cpp:177       Destructing connection #1295 to 0.0.0.0   
> ```

yo @nahuhh my node only banned IPs during the sync, after it was 100% synchronized no node was banned. Were those bans on your node happening after it was fully synchronized or during the synchronization?

**Comment by nahuhh** [comment]
@coffnix during sync

**Comment by coffnix** [comment]
> [@coffnix](https://github.com/coffnix) during sync

same here.... Try my script to auto unban. 

https://github.com/seraphis-migration/monero/issues/180#issuecomment-3405320886

**Comment by nahuhh** [comment]
1.4 auto-unbans after 2mins. I'm just sharing the lvl 2 log here

**Comment by j-berman** [comment]
Btw, [this one](https://github.com/seraphis-migration/monero/issues/180#issuecomment-3505567985) should be fixed by #265

**Comment by coffnix** [comment]
> Btw, [this one](https://github.com/seraphis-migration/monero/issues/180#issuecomment-3505567985) should be fixed by [#265](https://github.com/seraphis-migration/monero/pull/265)

The problem persists in version 1.5. My node was banned 47 times during a sync of the last 25,000 blocks, and it keeps banning. Look:

2026-01-12 01:54:27.112	I [116.203.98.127:56014 INC] dropping idle peer with negative score
2026-01-12 01:54:27.112	I Host 116.203.98.127 blocked.

<img width="1662" height="1153" alt="Image" src="https://github.com/user-attachments/assets/b05146bb-4511-46a7-81bd-8e5ce4733997" />
